### Task 1 
##### In a Jupyter Notebook (.ipynb) file, use pandas to load the data from the JSON dataset into a DataFrame. Explore the data.

In [3]:
# Import dependencies 

import pandas as pd
import json
from pandas.io.json import json_normalize

In [4]:
# Loading json file into a DataFrame

data = pd.read_json('dkdata.json')
data.head()

                                                data
0  {'payer_name': 'AZARBAYCAN METANOL KOMPANI MMC...
1  {'payer_name': 'LCM ALLIANCE LLP', 'payer_juri...
2  {'payer_name': 'SKN ELECTRICAL SERVICES LIMITE...
3  {'payer_name': 'METASTAR INVEST LLP', 'payer_j...
4  {'payer_name': 'METASTAR INVEST LLP', 'payer_j...

In [5]:
# Checking number of rows 

data.shape

(16940, 1)

In [6]:
# Underlying numpy arrays to see what columns to expect 

data.values

array([[{'payer_name': 'AZARBAYCAN METANOL KOMPANI MMC', 'payer_jurisdiction': 'AZ', 'payer_account': '33817018409333311204', 'source_file': 'pdf/LCM ALLIANCE Account statement 30.06.12-31.12.14.xml', 'amount_orig': 535470.0, 'id': 6049, 'beneficiary_type': 'Company', 'beneficiary_core': True, 'amount_orig_currency': 'USD', 'beneficiary_name': 'LCM ALLIANCE LLP', 'beneficiary_jurisdiction': 'GB', 'investigation': 'az', 'beneficiary_bank_country': 'EE', 'beneficiary_name_norm': 'LCM ALLIANCE LLP', 'payer_core': False, 'beneficiary_account': 'EE27 3300 3335 0561 0002', 'purpose': '1206295100052180 OCT4121800021 ADVANCE PAYM FOR THE INST RUMENTATIO N AND CONTROL CABLES BOM IN ACC WIT H THE CON TR DD 25.06.2012', 'date': '2012-06-30', 'amount_usd': 535470, 'amount_eur': '$431,762.31', 'payer_type': 'Company', 'payer_name_norm': 'AZARBAYCAN METANOL KOMPANI MMC', 'payer_bank_country': '33'}],
       [{'payer_name': 'LCM ALLIANCE LLP', 'payer_jurisdiction': 'GB', 'payer_account': 'EE27 3300 3335 0561 0002', 'source_file': 'pdf/LCM ALLIANCE Account statement 30.06.12-31.12.14.xml', 'amount_orig': -535000.0, 'id': 6050, 'beneficiary_type': 'Company', 'beneficiary_core': False, 'amount_orig_currency': 'USD', 'beneficiary_name': 'MOBILA LLP', 'beneficiary_jurisdiction': 'GB', 'investigation': 'az', 'beneficiary_bank_country': '33', 'beneficiary_name_norm': 'MOBILA LLP', 'payer_core': True, 'beneficiary_account': '333504500003', 'purpose': '1207035026699176 INVOICE.No 6215 DD 25.05.2012', 'date': '2012-07-03', 'amount_usd': 535000, 'amount_eur': '$423,688.44', 'payer_type': 'Company', 'payer_name_norm': 'LCM ALLIANCE LLP', 'payer_bank_country': 'EE'}],
       [{'payer_name': 'SKN ELECTRICAL SERVICES LIMITEDACCO', 'payer_jurisdiction': 'GB', 'payer_account': '20100374548222', 'source_file': 'pdf/METASTAR Account statement 30.06.12-31.12.14.xml', 'amount_orig': 90535.19, 'id': 10623, 'beneficiary_type': 'Company', 'beneficiary_core': True, 'amount_orig_currency': 'USD', 'beneficiary_name': 'METASTAR INVEST LLP', 'beneficiary_jurisdiction': 'GB', 'investigation': 'az', 'beneficiary_bank_country': 'EE', 'beneficiary_name_norm': 'METASTAR INVEST LLP', 'payer_core': False, 'beneficiary_account': 'EE77 3300 3334 8704 0004', 'purpose': '1207065103089249   /FEE/USD4,81', 'date': '2012-07-06', 'amount_usd': 90536, 'amount_eur': '$71,698.53', 'payer_type': 'Company', 'payer_name_norm': 'SKN ELECTRICAL SERVICES LIMITED', 'payer_bank_country': '20'}],
       ...,
       [{'payer_name': 'HILUX SERVICES LP', 'payer_jurisdiction': 'GB', 'payer_account': 'EE12 3300 3335 1615 0001', 'source_file': 'pdf/HILUX Account statement 30.06.12-31.12.14.xml', 'amount_orig': -42000.0, 'id': 4302, 'beneficiary_type': 'Person', 'beneficiary_core': False, 'amount_orig_currency': 'USD', 'beneficiary_name': 'VUGAR RZAYEV', 'beneficiary_jurisdiction': 'TR', 'investigation': 'az', 'beneficiary_bank_country': 'TR', 'beneficiary_name_norm': 'VUGAR RZAYEV', 'payer_core': True, 'beneficiary_account': 'TR920006200037300009087555', 'purpose': '1412315020689974 PAYMENT TO THE CONTRACT N 50 DD.15. 06. 2013 FOR SERVICE.', 'date': '2014-12-31', 'amount_usd': 42000, 'amount_eur': '$33,672.70', 'payer_type': 'Company', 'payer_name_norm': 'HILUX SERVICES LP', 'payer_bank_country': 'EE'}],
       [{'payer_name': 'FABERLEX LP', 'payer_jurisdiction': 'GB', 'payer_account': 'EE683300333516210006', 'source_file': 'pdf/HILUX Account statement 30.06.12-31.12.14.xml', 'amount_orig': 6000.0, 'id': 4301, 'beneficiary_type': 'Company', 'beneficiary_core': True, 'amount_orig_currency': 'USD', 'beneficiary_name': 'HILUX SERVICES LP', 'beneficiary_jurisdiction': 'GB', 'investigation': 'az', 'beneficiary_bank_country': 'EE', 'beneficiary_name_norm': 'HILUX SERVICES LP', 'payer_core': False, 'beneficiary_account': 'EE12 3300 3335 1615 0001', 'purpose': '1412315076170038 GROUP PAYMENT', 'date': '2014-12-31', 'amount_usd': 6000, 'amount_eur': '$4,810.39', 'payer_type': 'Company', 'payer_name_norm': 'FABERLEX LP', 'payer_bank_country': 'EE'}],
       [{'payer_name': 'RASMUS LP', 'payer_jurisdiction': 'GB', 'payer_account': 'EE923300333515620008', 'source_file': 'pdf/HILUX Account statement 30.06.12-31.12.14.xml', 'amount_orig': 2200000.0, 'id': 4300, 'beneficiary_type': 'Company', 'beneficiary_core': True, 'amount_orig_currency': 'USD', 'beneficiary_name': 'HILUX SERVICES LP', 'beneficiary_jurisdiction': 'GB', 'investigation': 'az', 'beneficiary_bank_country': 'EE', 'beneficiary_name_norm': 'HILUX SERVICES LP', 'payer_core': False, 'beneficiary_account': 'EE12 3300 3335 1615 0001', 'purpose': '1412315076256810 ACC TO CONTR 001 DD 03.06.2013, RETURN OF OVERPAID AMOUNT', 'date': '2014-12-31', 'amount_usd': 2200000, 'amount_eur': '$1,763,808.20', 'payer_type': 'Company', 'payer_name_norm': 'RASMUS LP', 'payer_bank_country': 'EE'}]],
      dtype=object)

In [7]:
# Unpacking nested column into a DataFrame utilizing json_normalize

with open('dkdata.json') as f:
    d = json.load(f)
    
dk_data = json_normalize(d['data'])
dk_data

,amount_eur,amount_orig,amount_orig_currency,amount_usd,beneficiary_account,beneficiary_bank_country,beneficiary_core,beneficiary_jurisdiction,beneficiary_name,beneficiary_name_norm,...,investigation,payer_account,payer_bank_country,payer_core,payer_jurisdiction,payer_name,payer_name_norm,payer_type,purpose,source_file
0,"$431,762.31",535470.00,USD,535470,EE27 3300 3335 0561 0002,EE,True,GB,LCM ALLIANCE LLP,LCM ALLIANCE LLP,...,az,33817018409333311204,33,False,AZ,AZARBAYCAN METANOL KOMPANI MMC,AZARBAYCAN METANOL KOMPANI MMC,Company,1206295100052180 OCT4121800021 ADVANCE PAYM FO...,pdf/LCM ALLIANCE Account statement 30.06.12-31...
1,"$423,688.44",-535000.00,USD,535000,333504500003,33,False,GB,MOBILA LLP,MOBILA LLP,...,az,EE27 3300 3335 0561 0002,EE,True,GB,LCM ALLIANCE LLP,LCM ALLIANCE LLP,Company,1207035026699176 INVOICE.No 6215 DD 25.05.2012,pdf/LCM ALLIANCE Account statement 30.06.12-31...
2,"$71,698.53",90535.19,USD,90536,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,20100374548222,20,False,GB,SKN ELECTRICAL SERVICES LIMITEDACCO,SKN ELECTRICAL SERVICES LIMITED,Company,"1207065103089249 /FEE/USD4,81",pdf/METASTAR Account statement 30.06.12-31.12....
3,"$71,686.50",-90520.00,USD,90520,333455870002,33,False,VG,INMAXO CAPITAL CORP,INMAXO CAPITAL CORP.,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207095022358525 DOGOVOR ZAYMA,pdf/METASTAR Account statement 30.06.12-31.12....
4,$47.52,-60.00,USD,60,333455870002,33,False,VG,INMAXO CAPITAL CORP,INMAXO CAPITAL CORP.,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207135024578077 DOGOVOR ZAYMA,pdf/METASTAR Account statement 30.06.12-31.12....
5,"$189,352.15",189352.15,EUR,239099,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,333455870002,33,False,VG,INMAXO CAPITAL CORP.,INMAXO CAPITAL CORP.,Company,CONTRACT N 001 DD 24.12.2009,pdf/METASTAR Account statement 30.06.12-31.12....
6,"$178,859.87",225850.00,USD,225850,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,333455870002,33,False,VG,INMAXO CAPITAL CORP.,INMAXO CAPITAL CORP.,Company,1207135026233261 CONTRACT N 001 DD 24.12.2009,pdf/METASTAR Account statement 30.06.12-31.12....
7,"$103,200.00",-103200.00,EUR,130313,333488110001,33,False,NZ,JETFIELD NETWORKS LIMITED,JETFIELD NETWORKS LIMITED,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,invoice 888 dd 09.06.2012,pdf/METASTAR Account statement 30.06.12-31.12....
8,"$94,000.00",-94000.00,EUR,118696,IT78T0605569721000000001000,IT,False,IT,ERREBI SPA,ERREBI SPA,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207165020172345 INVOICE 8456 DD 10.07.2012,pdf/METASTAR Account statement 30.06.12-31.12....
9,"$63,355.28",-80000.00,USD,80000,333484540002,33,False,GB,LOTA SALES LLP,LOTA SALES LLP,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207165025935425 DOGOVOR ZAYMA,pdf/METASTAR Account statement 30.06.12-31.12....
10,"$55,435.87",-70000.00,USD,70000,333484540002,33,False,GB,LOTA SALES LLP,LOTA SALES LLP,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207165022969353 DOGOVOR ZAYMA,pdf/METASTAR Account statement 30.06.12-31.12....
11,"$47,516.46",-60000.00,USD,60000,333499570009,33,False,UNKNOWN,ELEATEX TRADING S.L.,ELEATEX TRADING S.L.,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207165028140593 INVOICE 666 DD 06.06.2012,pdf/METASTAR Account statement 30.06.12-31.12....
12,"$43,556.76",-55000.00,USD,55000,TR410012300615100016777301,TR,False,TR,CST KIMYA SANAYI VE TICARET AS,CST KIMYA SANAYI VE TICARET AS,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207165020742469 INVOICE 743 DD 10.06.2012,pdf/METASTAR Account statement 30.06.12-31.12....
13,"$41,972.87",-53000.00,USD,53000,IT78H0306920409100000012385,IT,False,IT,SILVEA SCHIATTI+C.SRL,SILVEA SCHIATTI+C.SRL,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207165026491333 INVOICE 2-9 DD 11.07.2012,pdf/METASTAR Account statement 30.06.12-31.12....
14,"$29,250.34",-36935.00,USD,36935,TR070013400000000039500042,TR,False,TR,EGE KUR.KAMU FIN.VE TIC.MRKZ.SB.,EGE KUR.KAMU FIN.VE TIC.MRKZ.SB.,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207165022275789 AHMADOV ANAR SUBAR,pdf/METASTAR Account statement 30.06.12-31.12....
15,"$27,022.61",-34122.00,USD,34122,333499570009,33,False,UNKNOWN,ELEATEX TRADING S.L.,ELEATEX TRADING S.L.,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207165021570793 INVOICE 666 DD 06.06.2012,pdf/METASTAR Account statement 30.06.12-31.12....
16,"$3,567.69",-4505.00,USD,4505,TR240006200034100009092916,TR,False,TR,UNIVAR,UNIVAR KIMYA SANAYI VE DIS TIC LTD.,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207165022255697 INVOICE 785 DD 13.07.2012,pdf/METASTAR Account statement 30.06.12-31.12....
17,"$4,414.00",-4414.00,EUR,5574,DE96810700000210018800,DE,False,DE,MERTIK MAXITROL GMBH&CO KG,MERTIK MAXITROL GMBH & CO.KG,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207165020041457 INVOICE 01 DD 14.07.2012,pdf/METASTAR Account statement 30.06.12-31.12....
18,$791.94,-1000.00,USD,1000,333468790001,33,False,US,LINSTAR SYSTEMS CORP.,LINSTAR SYSTEMS CORP.,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207165025774169 INVOICE 01 DD 01.05.12,pdf/METASTAR Account statement 30.06.12-31.12....
19,$22.91,28.93,USD,29,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,333455870002,33,False,VG,INMAXO CAPITAL CORP.,INMAXO CAPITAL CORP.,Company,1207165020140189 CONTRACT N 001 DD 24.12.2009,pdf/METASTAR Account statement 30.06.12-31.12....
20,"$118,791.15",150000.00,USD,150000,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,333484540002,33,False,GB,LOTA SALES LLP,LOTA SALES LLP,Company,1207165021876577 DOGOVOR ZAYMA,pdf/METASTAR Account statement 30.06.12-31.12....
21,"$118,791.15",150000.00,USD,150000,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,333504500003,33,False,GB,MOBILA LLP,MOBILA LLP,Company,1207165026198353 INVOICE.No 69 DD 13.07.2012,pdf/METASTAR Account statement 30.06.12-31.12....
22,"$125,786.00",-158832.54,USD,158833,40702840722002001727,40,False,RU,OOO MAYAKPRINT,OOO MAYAKPRINT,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207175028296266 SHOT N 156 DD 05.04.2012,pdf/METASTAR Account statement 30.06.12-31.12....
23,"$150,000.00",-150000.00,EUR,189409,AE710200000025597675100,AE,False,AE,IMEX MOTORS L.L.C,IMEX MOTORS L.L.C.,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207175026172670 INVOICE 001 DD 12.02.2012 FOR...,pdf/METASTAR Account statement 30.06.12-31.12....
24,"$145,150.00",-145150.00,EUR,183284,333488110001,33,False,NZ,JETFIELD NETWORKS LIMITED,JETFIELD NETWORKS LIMITED,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,invoice 888 dd 09.06.2012,pdf/METASTAR Account statement 30.06.12-31.12....
25,"$87,984.65",-111100.00,USD,111100,333488110001,33,False,NZ,JETFIELD NETWORKS LIMITED,JETFIELD NETWORKS LIMITED,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207175024945082 invoice 888 dd 09.06.2012,pdf/METASTAR Account statement 30.06.12-31.12....
26,"$72,400.00",-72400.00,EUR,91421,333488110001,33,False,NZ,JETFIELD NETWORKS LIMITED,JETFIELD NETWORKS LIMITED,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,invoice 888 dd 09.06.2012,pdf/METASTAR Account statement 30.06.12-31.12....
27,"$68,366.00",-68366.00,EUR,86328,TR480006400000212780107701,TR,False,TR,CAHAN ISTANBUL DIS.TIC.LTD,CAHAN ISTANBUL DIS.TIC.LTD,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207175023760670 INVOICE 2345 DD 08.07.2012,pdf/METASTAR Account statement 30.06.12-31.12....
28,"$25,342.11",-32000.00,USD,32000,DE11400400280420274300,DE,False,DE,MTG HANDELS UND CONSULTING GMBH,MTG HANDELS UND CONSULTING GMBH,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207175025570082 INVOICE 531 DD 01.04.2012,pdf/METASTAR Account statement 30.06.12-31.12....
29,"$18,598.73",-23485.00,USD,23485,333499570009,33,False,UNKNOWN,ELEATEX TRADING S.L.,ELEATEX TRADING S.L.,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207175028320294 INVOICE 666 DD 06.06.2012,pdf/METASTAR Account statement 30.06.12-31.12....
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16910,"$105,000.00",-105000.00,EUR,130967,IT57S0504801639000000001821,IT,False,IT,FONDAZIONE NOVAE TERRAE,FONDAZIONE NOVAE TERRAE,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295036793430 PAYMENT TO THE CONTRACT N.W/N...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16911,"$91,000.00",-91000.00,EUR,113505,EE683300333516210006,EE,False,GB,FABERLEX LP,FABERLEX LP,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,GROUP PAYMENT,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16912,"$60,210.00",-75100.00,USD,75100,LI0408812105030530001,LI,False,VG,RENAISSANCE ASSOCIATES S.A.,RENAISSANCE ASSOCIATES S.A.,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295020996358 PAYMENT TO THE CONTRACT N 01 ...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16913,"$66,338.00",-66338.00,EUR,82744,TR020020600033019706260102,TR,False,TR,KARAT GUC SISTEMLERI SAN.VE TIC.,KARAT GUC SISTEMLERI SAN.VE TIC.,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295026084242 PAYMENT TO THE INVOICE N. N1-...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16914,"$64,825.00",-64825.00,EUR,80857,NL44DEUT0265165296,NL,False,NL,ENZA ZADEN EXPORT B.V,ENZA ZADEN EXPORT B.V.,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295038278546 PAYMENT TO THE INVOICE N 9554...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16915,"$55,007.00",-55007.00,EUR,68611,LI7908812105030540000,LI,False,US,PARY INTERNATIONAL,PARY INTERNATIONAL INC.,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295036593302 PAYMENT TO THE CONTRACT N 038...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16916,"$40,888.28",-51000.00,USD,51000,AE650030010220620394001,AE,False,AE,ZEN TRAX INC.,ZEN TRAX INC.,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295022190790 PAYMENT TO THE CONTRACT N 6 D...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16917,"$32,069.24",-40000.00,USD,40000,102558,10,False,UNKNOWN,CEMENA SERVICES LIMITED,CEMENA SERVICES LIMITED,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295026476422 PAYMENT TO THE CONTRACT N.28 ...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16918,"$25,000.00",-25000.00,EUR,31183,CZ5527000000002107039983,CZ,False,CZ,GLAMOUR DIAMOND S.R.O.,GLAMOUR DIAMOND S.R.O.,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295034398998 PAYMENT TO THE INVOICE N.16/1...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16919,"$20,043.28",-25000.00,USD,25000,475458233237,47,False,CN,"JIANGSU UNBEATABLE RADIATOR CO.,LTD","JIANGSU UNBEATABLE RADIATOR CO., LTD",...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295023479022 PAYMENT TO THE INVOICE N.ZA00...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16920,"$21,839.20",-21839.20,EUR,27241,FR7630003000800002030076732,FR,False,FR,GSN SEMENCES S.A.S,GSN SEMENCES S.A.S,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295036178610 PAYMENT TO THE CONTRAKT GSN/F...,pdf/HILUX Allegato 4.xml
16921,"$16,034.62",-20000.00,USD,20000,LV59RTMB0000611806345,LV,False,VG,ODEN ASSETS LTD,ODEN ASSETS LTD,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295031262686 PAYMENT TO THE CONTRACT N 398...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16922,"$7,668.05",-9564.37,USD,9565,TR420001200938800053000248,TR,False,TR,YIGITLER FLANS,YIGITLER FLANS,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295024693494 PAYMENT TO THE INVOICE N.H-8 ...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16923,"$7,040.00",-7040.00,EUR,8781,TR230006400000211373371180,TR,False,TR,SAYGIN HIDROFOR VE POMPA SIS.SAN.,SAYGIN HIDROFOR VE POMPA SIS. SAN.,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295020010390 PAYMENT TO THE INVOICE N.3281...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16924,"$6,876.00",-6876.00,EUR,8577,TR030006400000213930001995,TR,False,TR,DURKO CEVRE ENERJI TEKNIGI VE TIC.,DURKO CEVRE ENERJI TEKNIGI VE TIC.,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295024599126 PAYMENT TO THE INVOICE N.2 DD...,pdf/HILUX Allegato 4.xml
16925,"$1,892.00",-1892.00,EUR,2360,TR950003200014500000226115,TR,False,TR,GRUNDFOS POMPA SAN.TIC.LTD.STI.,GRUNDFOS POMPA SAN.TIC.LTD.STI.,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295022404822 PAYMENT FOR WATER PIPES UNDER...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16926,"$1,547.34",1930.00,USD,1930,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,EE083300333513530006,EE,False,GB,CROSSPARK LINES LLP,CROSSPARK LINES LLP,Company,1412295072206634 inv. no 1916 for electro equi...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16927,"$300,000.00",300000.00,EUR,374191,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,LV87AIZK0001140110799,LV,False,CY,CASPIAN MOBILE LTD.,CASPIAN MOBILE LTD.,Company,1412295105818062 INVOICE NO P230400506 FOR ELE...,pdf/HILUX Allegato 4.xml
16928,"$4,409,477.61",5499946.50,USD,5499947,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,AZ18IBAZ40150018404004037267,AZ,False,AZ,BAKTELEKOM MMC,BAKTELEKOM MMC,Company,1412265102334077 CONTRAKT N47 03.11.2014 /FEE...,pdf/HILUX Allegato 4.xml
16929,"$4,712,772.44",5878246.50,USD,5878247,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,AZ18IBAZ40150018404004037267,AZ,False,AZ,BAKTELEKOM MMC,BAKTELEKOM MMC,Company,1412295108133598 CONTRAKT N47 03.11.2014 /FEE...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16930,"$300,000.00",-300000.00,EUR,374191,CH62007645958754C000C,CH,False,CH,CHIANCIANESI AND LONGONI,CHIANCIANESI AND LONGONI,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412305035411964 PAYMENT TO THE INVOICE N.69 D...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16931,"$230,000.00",-230000.00,EUR,286880,LV48AIZK0001140094623,LV,False,UNKNOWN,CASPIAN INVEST LIMITED,CASPIAN INVEST LIMITED,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295033085006 PAYMENT TO THE INVOICE N.39 D...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16932,"$134,600.00",-134600.00,EUR,167887,NL91DEUT0471363170,NL,False,NL,BAARS CONFLOAT BV,BAARS CONFLOAT BV,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295030890702 PAYMENT TO THE INVOICE N.1400...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16933,"$962,077.20",-1200000.00,USD,1200000,EE073300333514840009,EE,False,GB,DATEMILE ALLIANCE LLP,DATEMILE ALLIANCE LLP,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412315075078582 PAYMENT TO THE CONTRACT N 55 ...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16934,"$617,332.87",-770000.00,USD,770000,EE873300333520140007,EE,False,GB,RICHFIELD TRADING L.P.,RICHFIELD TRADING L.P.,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412315074763930 PAYMENT TO THE CONTRACT N.12/...,pdf/HILUX Allegato 4.xml
16935,"$80,173.10",-100000.00,USD,100000,EE123300333505040009,EE,False,GB,BONDWEST LLP,BONDWEST LLP,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412315077469974 PAYMENT TO THE CONTRACT N 28 ...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16936,"$70,552.33",-88000.00,USD,88000,EE303300333517290009,EE,False,GB,CITYPORT CONTRACTS L.P.,CITYPORT CONTRACTS L.P.,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412315075275670 CONTRACT N 0042 DD 01.08.2013,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16937,"$33,672.70",-42000.00,USD,42000,TR920006200037300009087555,TR,False,TR,VUGAR RZAYEV,VUGAR RZAYEV,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412315020689974 PAYMENT TO THE CONTRACT N 50 ...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16938,"$4,810.39",6000.00,USD,6000,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,EE683300333516210006,EE,False,GB,FABERLEX LP,FABERLEX LP,Company,1412315076170038 GROUP PAYMENT,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16939,"$1,763,808.20",2200000.00,USD,2200000,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,EE923300333515620008,EE,False,GB,RASMUS LP,RASMUS LP,Company,1412315076256810 ACC TO CONTR 001 DD 03.06.201...,pdf/HILUX Account statement 30.06.12-31.12.14.xml

### Basic Analysis 

Now that we were able to properly load all the content of the file into a DataFrame we are going to look for basic informations like, duplicate names, missing values, account numbers etc...

In [8]:
# Checking for any missing value and summing them up

dk_data.isnull().sum()

amount_eur                    0
amount_orig                   0
amount_orig_currency          0
amount_usd                    0
beneficiary_account           4
beneficiary_bank_country      4
beneficiary_core              0
beneficiary_jurisdiction      0
beneficiary_name              0
beneficiary_name_norm         0
beneficiary_type              0
date                          0
id                            0
investigation                 0
payer_account               115
payer_bank_country          115
payer_core                    0
payer_jurisdiction            0
payer_name                    0
payer_name_norm               0
payer_type                    0
purpose                       0
source_file                   0
dtype: int64

On the above cell we have learned that there are 115 payers's bank account missing, consequentely 115 payer's bank country missing. Also, we noticed that there are 4 beneficiary bank account missing, consequentely 4 beneficiary bank country missing. I'm still not sure what that means, however, it raises questions as I wonder if they are somehow corelated.

In [22]:
# Pulling data that only contains missing information from initial 
# dataframe

dk_dataNull = dk_data[dk_data.isnull().any(axis=1)]
dk_dataNull

,amount_eur,amount_orig,amount_orig_currency,amount_usd,beneficiary_account,beneficiary_bank_country,beneficiary_core,beneficiary_jurisdiction,beneficiary_name,beneficiary_name_norm,...,investigation,payer_account,payer_bank_country,payer_core,payer_jurisdiction,payer_name,payer_name_norm,payer_type,purpose,source_file
67,"$132,789.00",132789.00,EUR,167676,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,None,None,False,DE,DEUTDEFFXXX,DEUTDEFFXXX,Invalid,1207185100280220 RTN 1207135025890645/7033/ 13...,pdf/METASTAR Account statement 30.06.12-31.12....
121,"$39,567.35",49962.50,USD,49963,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,None,None,False,CN,BKCHCNBJ,BKCHCNBJ,Invalid,1207245104516412 345587 INMAXO CAPITAL CORP./...,pdf/METASTAR Account statement 30.06.12-31.12....
306,"$1,468.05",-1800.00,USD,1800,None,None,False,UNKNOWN,CONTINENTAL ENGINES,CONTINENTAL ENGINES,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1208105026359433 ORDER NUMBER NO 1179550 DD 18...,pdf/METASTAR Account statement 30.06.12-31.12....
308,"$66,871.29",66871.29,EUR,81992,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,None,None,False,DE,DEUTDEFFXXX,DEUTDEFFXXX,Invalid,1208095105222495 RETURN OF P/O 159/12073050228...,pdf/METASTAR Account statement 30.06.12-31.12....
451,"$30,111.44",36920.00,USD,36920,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,None,None,False,TR,DENITRIS,DENITRIS,Invalid,1208275104667672 RTN P/O 1207265020271628/132...,pdf/METASTAR Account statement 30.06.12-31.12....
509,"$3,262.34",4000.00,USD,4000,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,None,None,False,US,TDOMUS33,TDOMUS33,Invalid,1208305106394756 RTN P/O 1208225027994320/301...,pdf/METASTAR Account statement 30.06.12-31.12....
603,"$12,618.69",10000.00,GBP,15872,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,None,None,False,GB,BARCGB22,BARCGB22,Invalid,1209055105244285 RTN P/O 1208315022336943/361...,pdf/METASTAR Account statement 30.06.12-31.12....
1210,$178.33,178.33,EUR,230,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,None,None,False,US,JOHNS HOPKINS MEDICINE,JOHNS HOPKINS MEDICINE,Company,1210125023968240 EYYUBOV YAQUB + STATEMENT N 2...,pdf/METASTAR Account statement 30.06.12-31.12....
1211,"$1,242.04",1242.04,EUR,1601,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,None,None,False,DE,NORSDE71,NORSDE71,Invalid,1210125104899072 RTN P/O 1210105026740299/638...,pdf/METASTAR Account statement 30.06.12-31.12....
2923,"$1,844.77",1500.00,GBP,2437,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,None,None,False,GB,BARCGB22,BARCGB22,Invalid,1301255101707659 RTN P/O 1301185022790441/126...,pdf/METASTAR Account statement 30.06.12-31.12....
3084,"$8,790.90",12000.00,USD,12000,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,None,None,False,CA,TD CANADA TRUST,TD CANADA TRUST,Company,1302045024069972 INVOICE 46 DD 01.02.2013,pdf/METASTAR Account statement 30.06.12-31.12....
3508,"$45,732.46",62427.00,USD,62427,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,None,None,False,CA,ROYCCAT2X,ROYCCAT2X,Invalid,1302225108154541 RTN P/O 1302015024871561/133...,pdf/METASTAR Account statement 30.06.12-31.12....
3510,"$73,215.40",99942.53,USD,99943,EE27 3300 3335 0561 0002,EE,True,GB,LCM ALLIANCE LLP,LCM ALLIANCE LLP,...,az,None,None,False,HK,HASEHKHH,HASEHKHH,Invalid,1302225106497517 RTN P/O 1301315024848275/425...,pdf/LCM ALLIANCE Account statement 30.06.12-31...
3598,"$2,131.43",-2909.50,USD,2910,None,None,False,UNKNOWN,MICROCOPY,MICROCOPY,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1302265026564645 INVOICE SO12000014 DD 13/12/2...,pdf/METASTAR Account statement 30.06.12-31.12....
3677,"$14,483.01",19770.00,USD,19770,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,None,None,False,DE,OWHBDEFF,OWHBDEFF,Invalid,1302285104521519 RTN P/O 1302255028309703/147...,pdf/METASTAR Account statement 30.06.12-31.12....
4229,"$500,000.00",500000.00,EUR,651330,EE27 3300 3335 0561 0002,EE,True,GB,LCM ALLIANCE LLP,LCM ALLIANCE LLP,...,az,None,None,False,AZ,PANO ASC,PANO ASC,Company,1303145108328870 PREPAYMENT FOR CNTR.15.01.13,pdf/LCM ALLIANCE Account statement 30.06.12-31...
4441,"$274,862.00",274862.00,EUR,358052,EE27 3300 3335 0561 0002,EE,True,GB,LCM ALLIANCE LLP,LCM ALLIANCE LLP,...,az,None,None,False,DE,DEUTDEFFXXX,DEUTDEFFXXX,Invalid,1303255103061595 RTN 1303205022972973/620/ EUR...,pdf/LCM ALLIANCE Account statement 30.06.12-31...
4823,"$360,438.00",360438.00,EUR,462652,EE27 3300 3335 0561 0002,EE,True,GB,LCM ALLIANCE LLP,LCM ALLIANCE LLP,...,az,None,None,False,AE,TRADEMAX GENERAL TRADING CO.LTD,TRADEMAX GENERAL TRADING CO.LTD,Company,tagastus Muud põhjused,pdf/LCM ALLIANCE Account statement 30.06.12-31...
5073,"$475,578.00",475578.00,EUR,610443,EE27 3300 3335 0561 0002,EE,True,GB,LCM ALLIANCE LLP,LCM ALLIANCE LLP,...,az,None,None,False,DE,DEUTDEFFXXX,DEUTDEFFXXX,Invalid,1304105101108652 RTN 1304095025230674/722/ EUR...,pdf/LCM ALLIANCE Account statement 30.06.12-31...
5124,"$103,053.00",103053.00,EUR,132277,EE27 3300 3335 0561 0002,EE,True,GB,LCM ALLIANCE LLP,LCM ALLIANCE LLP,...,az,None,None,False,DE,DEUTDEFFXXX,DEUTDEFFXXX,Invalid,1304115107552694 RTN 1304035020844848/730/ EUR...,pdf/LCM ALLIANCE Allegato 33.xml
5126,"$122,920.00",122920.00,EUR,157778,EE27 3300 3335 0561 0002,EE,True,GB,LCM ALLIANCE LLP,LCM ALLIANCE LLP,...,az,None,None,False,DE,DEUTDEFFXXX,DEUTDEFFXXX,Invalid,1304115106452630 RTN 1304035022519280/711/ EUR...,pdf/LCM ALLIANCE Account statement 30.06.12-31...
5590,"$154,379.15",198158.00,USD,198158,EE27 3300 3335 0561 0002,EE,True,GB,LCM ALLIANCE LLP,LCM ALLIANCE LLP,...,az,None,None,False,LI,HYIBLI22,HYIBLI22,Invalid,1304245100733313 RTN P/O 1304175020245693/775...,pdf/LCM ALLIANCE Account statement 30.06.12-31...
6232,"$46,861.45",1927646.00,RUB,61781,EE27 3300 3335 0561 0002,EE,True,GB,LCM ALLIANCE LLP,LCM ALLIANCE LLP,...,az,None,None,False,RU,INN3018016381,INN3018016381,Company,tagastus Saaja konto on vale,pdf/LCM ALLIANCE Account statement 30.06.12-31...
6234,"$56,537.53",2325672.00,RUB,74538,EE27 3300 3335 0561 0002,EE,True,GB,LCM ALLIANCE LLP,LCM ALLIANCE LLP,...,az,None,None,False,RU,INN3016055642,INN3016055642,Company,tagastus Saaja konto on vale,pdf/LCM ALLIANCE Account statement 30.06.12-31...
6236,"$88,271.74",3631059.00,RUB,116375,EE27 3300 3335 0561 0002,EE,True,GB,LCM ALLIANCE LLP,LCM ALLIANCE LLP,...,az,None,None,False,RU,INN5918000980,INN5918000980,Company,tagastus Saaja konto on vale,pdf/LCM ALLIANCE Account statement 30.06.12-31...
6237,"$90,383.84",3717940.00,RUB,119159,EE27 3300 3335 0561 0002,EE,True,GB,LCM ALLIANCE LLP,LCM ALLIANCE LLP,...,az,None,None,False,RU,INN5906109648,INN5906109648,Company,tagastus Saaja konto on vale,pdf/LCM ALLIANCE Account statement 30.06.12-31...
6385,"$155,167.34",204567.00,USD,204567,EE27 3300 3335 0561 0002,EE,True,GB,LCM ALLIANCE LLP,LCM ALLIANCE LLP,...,az,None,None,False,LI,HYIBLI22,HYIBLI22,Invalid,1305165105172579 RTN P/O 1305085022069552/813...,pdf/LCM ALLIANCE Account statement 30.06.12-31...
6493,"$204,874.00",204874.00,EUR,270099,EE27 3300 3335 0561 0002,EE,True,GB,LCM ALLIANCE LLP,LCM ALLIANCE LLP,...,az,None,None,False,GB,ALPS VENTURES LIMITED,ALPS VENTURES LIMITED,Company,tagastus Muud põhjused,pdf/LCM ALLIANCE Account statement 30.06.12-31...
6636,$20.36,26.84,USD,27,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,None,None,False,DE,SABA CARS GERMANY GMBH,SABA CARS Germany GmbH,Company,COMMISSION/FEE CREDIT,pdf/METASTAR Account statement 30.06.12-31.12....
6643,"$126,200.00",126200.00,EUR,166378,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,None,None,False,DE,SABA CARS GERMANY GMBH,SABA CARS Germany GmbH,Company,tagastus Kliendi korralduse alusel,pdf/METASTAR Account statement 30.06.12-31.12....
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12014,"$55,541.54",75482.00,USD,75482,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,LI,VOAGLI22,VOAGLI22,Invalid,1312125104984710 RTN P/O 1312055028047741/739...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
12160,"$39,950.00",39950.00,EUR,54293,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,DE,DEUTDEFFXXX,DEUTDEFFXXX,Invalid,1312205107645033 RTN 1312185032422144/881/ EUR...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
12383,"$50,869.90",69975.33,USD,69976,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,TR,YAPITRIS,YAPITRIS,Invalid,1401145100937340 POLUX MANAGEMENT LP 351622/RT...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
12572,"$8,152.68",10000.00,CHF,11215,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,CH,UBSWCHZH80A,UBSWCHZH80A,Invalid,1401305101090511 RTN P/O 1401275020233987/1169...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
12599,"$39,950.00",39950.00,EUR,53887,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,DE,DEUTDEFFXXX,DEUTDEFFXXX,Invalid,1402045105929341 RTN 1401275038214243/1161/ EU...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
12829,"$11,120.60",15000.00,USD,15000,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,CN,"APOLLO(CHINA) CO.,LTD","APPOLLO (CHINA) CO., LTD",Company,tagastus Kliendi korralduse alusel,pdf/HILUX Account statement 30.06.12-31.12.14.xml
12872,$38.65,53.35,USD,54,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,TR,KREN VINC MAKINA DERI URN.,KREN VINC MAKINA DERI URN.,Company,COMMISSION/FEE CREDIT,pdf/HILUX Account statement 30.06.12-31.12.14.xml
12873,"$4,075.00",4075.00,EUR,5625,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,TR,KREN VINC MAKINA DERI URN.,KREN VINC MAKINA DERI URN.,Company,"CANCELLATION, IBAN AND BIC DO NOT MATCH",pdf/HILUX Account statement 30.06.12-31.12.14.xml
12900,$38.65,53.35,USD,54,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,TR,ZER KELEPCE IMALAT VE TICARET,ZER KELEPCE IMALAT VE TICARET,Company,COMMISSION/FEE CREDIT,pdf/HILUX Account statement 30.06.12-31.12.14.xml
12901,"$3,172.03",4378.00,USD,4378,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,TR,ZER KELEPCE IMALAT VE TICARET,ZER KELEPCE IMALAT VE TICARET,Company,"CANCELLATION, IBAN AND BIC DO NOT MATCH",pdf/HILUX Account statement 30.06.12-31.12.14.xml
12940,"$211,411.00",211411.00,EUR,291787,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,DE,DEUTDEFFXXX,DEUTDEFFXXX,Invalid,1403065103964208 RTN 1402255023098505211/1373/...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
12941,"$399,978.00",399978.00,EUR,552045,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,DE,DEUTDEFFXXX,DEUTDEFFXXX,Invalid,1403065105061488 RTN 1402265026149031/1399/ 40...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
12943,"$912,012.74",1258749.00,USD,1258749,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,AE,EBILAEAD,EBILAEAD,Invalid,1403075101465314 RTN P/O 1402255024202969/1384...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
12946,"$10,004.43",13808.00,USD,13808,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,AE,EBILAEAD,EBILAEAD,Invalid,1403105102782180 RTN P/O 1402195025228259/1330...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
12948,"$181,097.80",249949.00,USD,249949,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,AE,EBILAEAD,EBILAEAD,Invalid,1403105105206516 RTN P/O 1402255027684457/1383...,pdf/HILUX Allegato 4.xml
12949,"$673,784.32",929949.00,USD,929949,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,AE,EBILAEAD,EBILAEAD,Invalid,1403105103859268 RTN P/O 1402195021836739/1327...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
12974,$38.99,53.81,USD,54,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,TR,BORFIT BORU VE EK PARCALARI SAN.TIC,BORFIT BORU VE EK PARCALARI SAN.TIC,Company,COMMISSION/FEE CREDIT,pdf/HILUX Account statement 30.06.12-31.12.14.xml
12975,"$4,000.00",4000.00,EUR,5521,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,TR,BORFIT BORU VE EK PARCALARI SAN.TIC,BORFIT BORU VE EK PARCALARI SAN.TIC,Company,tagastus Kliendi korralduse alusel,pdf/HILUX Account statement 30.06.12-31.12.14.xml
13274,"$82,539.00",82539.00,EUR,113853,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,DE,DEUTDEFFXXX,DEUTDEFFXXX,Invalid,1404115108111226 RTN 1404035038169688/1686/ E...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
13536,"$7,135.00",7135.00,EUR,9896,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,DE,DEUTDEFFXXX,DEUTDEFFXXX,Invalid,1405095100142226 RTN 1404165035641537/1788/ EU...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
14156,"$8,238.26",11227.00,USD,11227,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,GB,BOTKGB2L,BOTKGB2L,Invalid,1406275102929501 RTN P/O 1406175027888075/2336...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
14317,"$46,249.25",63265.00,USD,63265,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,NL,KABANL2A,KABANL2A,Invalid,1407085104792816 RETURN OF P/O 2481/1406305025...,pdf/HILUX Allegato 4.xml
15343,"$53,315.99",70000.00,USD,70000,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,GB,MASHREQBANK PSC,MASHREQBANK PSC,Company,1409155106843656 RETURN OF P/O 3094/1408215024...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
15613,"$93,403.52",122632.00,USD,122632,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,IL,IDBLILIT,IDBLILIT,Invalid,1409265107954337 RTN P/O 1409155025068798/3471...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
15993,"$131,950.00",131950.00,EUR,166510,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,DE,DEUTDEFFXXX,DEUTDEFFXXX,Invalid,1410225106204635 RTN 1410085026453238/3798/ EU...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16089,"$349,950.00",349950.00,EUR,441607,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,DE,DEUTDEFFXXX,DEUTDEFFXXX,Invalid,1410295106744555 RTN 1410095020828956/3812/ EU...,pdf/HILUX Allegato 4.xml
16171,"$292,950.00",292950.00,EUR,366914,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,DE,DEUTDEFFXXX,DEUTDEFFXXX,Invalid,1411045100888700 RTN 1410105025542954/3830/ 29...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16285,$38.57,48.31,USD,49,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,VG,ODEN ASSETS LTD,ODEN ASSETS LTD,Company,COMMISSION/FEE CREDIT,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16288,"$23,952.54",30000.00,USD,30000,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,VG,ODEN ASSETS LTD,ODEN ASSETS LTD,Company,tagastus Kliendi korralduse alusel,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16692,"$9,980.00",9980.00,EUR,12449,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,None,None,False,DE,DEUTDEFFXXX,DEUTDEFFXXX,Invalid,1412095102798888 RTN 1412045036171460/4378/ EU...,pdf/HILUX Allegato 4.xml

In [34]:
# Count of the unique payers name 
# Name of the unique payers name 

print(dk_dataNull.payer_name.nunique())
dk_dataNull.payer_name.unique()

70

array(['DEUTDEFFXXX', 'BKCHCNBJ', 'METASTAR INVEST LLP', 'DENITRIS',
       'TDOMUS33', 'BARCGB22', 'JOHNS HOPKINS MEDICINE', 'NORSDE71',
       'TD CANADA TRUST', 'ROYCCAT2X', 'HASEHKHH', 'OWHBDEFF', 'PANO ASC',
       'TRADEMAX GENERAL TRADING CO.LTD', 'HYIBLI22', 'INN3018016381',
       'INN3016055642', 'INN5918000980', 'INN5906109648',
       'ALPS VENTURES LIMITED', 'SABA CARS GERMANY GMBH',
       'MR RAHEB GENERAL TRADING', 'INN3016043171', 'INN3017030922',
       'In favour JSC Freight One', 'SHANGHAI PUDONG DEV BANK',
       'SBERBANK OF RUSSIA', 'INN6234018156',
       'ALGHARABALLY NATIONAL TRADING',
       'UNTEL KABLOLARI SANAYI VE TICARET', 'KEMIRA OYJ',
       'UCGE ELEKTONIK CIH.BILG.VE MAG.EKP.', 'GENERAL TURBO S.A',
       'MARAK CO LIMITED', 'PACIFIC LAMPS AND ELECTRICAL',
       'QIN YI TRADING CO.,LIMITED', 'HAENG SUNG ELECTRONIC CO',
       'YIWU HONGCHENG TRADING CO.,LTD', 'SANDLAND OVERSEAS',
       'XINJIANG KAIMEI INTERNATIONAL', 'RUSSIAN AGRICULTURAL BANK',
       'BKTRUS33', 'NRAKAEAK', 'OOO DOZA AQRO', 'COBADEFFXXX', 'PAHAAZ22',
       'MEGA TURIZM TASIMACILIK ,TARIM ORMA', 'Miss Aruna Dackeviciene',
       'AVROMED COMPANY', 'ZENIT', 'HSBCHKHHHKH', 'RAAD KADHIM',
       'HILUX SERVICES LP', 'INN4028023076',
       'ASEL DIS TICARET VE PAZARLAMA LTD S',
       'YOTO IMPORT&EXPORT CO., LTD', 'OOO PREDPRIATIE PRODUKTOV PITANIA',
       'VOAGLI22', 'YAPITRIS', 'UBSWCHZH80A', 'APOLLO(CHINA) CO.,LTD',
       'KREN VINC MAKINA DERI URN.', 'ZER KELEPCE IMALAT VE TICARET',
       'EBILAEAD', 'BORFIT BORU VE EK PARCALARI SAN.TIC', 'BOTKGB2L',
       'KABANL2A', 'MASHREQBANK PSC', 'IDBLILIT', 'ODEN ASSETS LTD'],
      dtype=object)

In [32]:
# Count of the unique beneficiary name 
# Name of the unique beneficiary name 

print(dk_dataNull.beneficiary_name.nunique())
dk_dataNull.beneficiary_name.unique()

7

array(['METASTAR INVEST LLP', 'CONTINENTAL ENGINES', 'LCM ALLIANCE LLP',
       'MICROCOPY', 'POLUX MANAGEMENT LP', 'HILUX SERVICES LP',
       'TURBILLION LLC'], dtype=object)

In [37]:
# Exporting dk_data dataframe into a csv file

dk_data.to_csv('dk_data.csv', index=False)