# Task 1

#### In a Jupyter Notebook (.ipynb) file, use pandas to load the data from the JSON dataset into a DataFrame. Explore the data.

In [16]:
# Import dependencies 

import pandas as pd
import json
from pandas.io.json import json_normalize

#### Loading the JSON file into a DataFrame

In [17]:
data = pd.read_json('dkdata.json')
data.head()

                                                data
0  {'payer_name': 'AZARBAYCAN METANOL KOMPANI MMC...
1  {'payer_name': 'LCM ALLIANCE LLP', 'payer_juri...
2  {'payer_name': 'SKN ELECTRICAL SERVICES LIMITE...
3  {'payer_name': 'METASTAR INVEST LLP', 'payer_j...
4  {'payer_name': 'METASTAR INVEST LLP', 'payer_j...

#### The outcome of my first tentative to load the JSON file into a DataFrame returned with a nested column. In order to proceed I need to flatten the whole column and unpack into a new DataFrame.

In [21]:
# Unpacking nested column into a DataFrame utilizing json_normalize

with open('dkdata.json') as f:
    d = json.load(f)
    
dk_data = json_normalize(d['data'])
dk_data

,amount_eur,amount_orig,amount_orig_currency,amount_usd,beneficiary_account,beneficiary_bank_country,beneficiary_core,beneficiary_jurisdiction,beneficiary_name,beneficiary_name_norm,...,investigation,payer_account,payer_bank_country,payer_core,payer_jurisdiction,payer_name,payer_name_norm,payer_type,purpose,source_file
0,"$431,762.31",535470.00,USD,535470,EE27 3300 3335 0561 0002,EE,True,GB,LCM ALLIANCE LLP,LCM ALLIANCE LLP,...,az,33817018409333311204,33,False,AZ,AZARBAYCAN METANOL KOMPANI MMC,AZARBAYCAN METANOL KOMPANI MMC,Company,1206295100052180 OCT4121800021 ADVANCE PAYM FO...,pdf/LCM ALLIANCE Account statement 30.06.12-31...
1,"$423,688.44",-535000.00,USD,535000,333504500003,33,False,GB,MOBILA LLP,MOBILA LLP,...,az,EE27 3300 3335 0561 0002,EE,True,GB,LCM ALLIANCE LLP,LCM ALLIANCE LLP,Company,1207035026699176 INVOICE.No 6215 DD 25.05.2012,pdf/LCM ALLIANCE Account statement 30.06.12-31...
2,"$71,698.53",90535.19,USD,90536,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,20100374548222,20,False,GB,SKN ELECTRICAL SERVICES LIMITEDACCO,SKN ELECTRICAL SERVICES LIMITED,Company,"1207065103089249 /FEE/USD4,81",pdf/METASTAR Account statement 30.06.12-31.12....
3,"$71,686.50",-90520.00,USD,90520,333455870002,33,False,VG,INMAXO CAPITAL CORP,INMAXO CAPITAL CORP.,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207095022358525 DOGOVOR ZAYMA,pdf/METASTAR Account statement 30.06.12-31.12....
4,$47.52,-60.00,USD,60,333455870002,33,False,VG,INMAXO CAPITAL CORP,INMAXO CAPITAL CORP.,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207135024578077 DOGOVOR ZAYMA,pdf/METASTAR Account statement 30.06.12-31.12....
5,"$189,352.15",189352.15,EUR,239099,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,333455870002,33,False,VG,INMAXO CAPITAL CORP.,INMAXO CAPITAL CORP.,Company,CONTRACT N 001 DD 24.12.2009,pdf/METASTAR Account statement 30.06.12-31.12....
6,"$178,859.87",225850.00,USD,225850,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,333455870002,33,False,VG,INMAXO CAPITAL CORP.,INMAXO CAPITAL CORP.,Company,1207135026233261 CONTRACT N 001 DD 24.12.2009,pdf/METASTAR Account statement 30.06.12-31.12....
7,"$103,200.00",-103200.00,EUR,130313,333488110001,33,False,NZ,JETFIELD NETWORKS LIMITED,JETFIELD NETWORKS LIMITED,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,invoice 888 dd 09.06.2012,pdf/METASTAR Account statement 30.06.12-31.12....
8,"$94,000.00",-94000.00,EUR,118696,IT78T0605569721000000001000,IT,False,IT,ERREBI SPA,ERREBI SPA,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207165020172345 INVOICE 8456 DD 10.07.2012,pdf/METASTAR Account statement 30.06.12-31.12....
9,"$63,355.28",-80000.00,USD,80000,333484540002,33,False,GB,LOTA SALES LLP,LOTA SALES LLP,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207165025935425 DOGOVOR ZAYMA,pdf/METASTAR Account statement 30.06.12-31.12....
10,"$55,435.87",-70000.00,USD,70000,333484540002,33,False,GB,LOTA SALES LLP,LOTA SALES LLP,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207165022969353 DOGOVOR ZAYMA,pdf/METASTAR Account statement 30.06.12-31.12....
11,"$47,516.46",-60000.00,USD,60000,333499570009,33,False,UNKNOWN,ELEATEX TRADING S.L.,ELEATEX TRADING S.L.,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207165028140593 INVOICE 666 DD 06.06.2012,pdf/METASTAR Account statement 30.06.12-31.12....
12,"$43,556.76",-55000.00,USD,55000,TR410012300615100016777301,TR,False,TR,CST KIMYA SANAYI VE TICARET AS,CST KIMYA SANAYI VE TICARET AS,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207165020742469 INVOICE 743 DD 10.06.2012,pdf/METASTAR Account statement 30.06.12-31.12....
13,"$41,972.87",-53000.00,USD,53000,IT78H0306920409100000012385,IT,False,IT,SILVEA SCHIATTI+C.SRL,SILVEA SCHIATTI+C.SRL,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207165026491333 INVOICE 2-9 DD 11.07.2012,pdf/METASTAR Account statement 30.06.12-31.12....
14,"$29,250.34",-36935.00,USD,36935,TR070013400000000039500042,TR,False,TR,EGE KUR.KAMU FIN.VE TIC.MRKZ.SB.,EGE KUR.KAMU FIN.VE TIC.MRKZ.SB.,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207165022275789 AHMADOV ANAR SUBAR,pdf/METASTAR Account statement 30.06.12-31.12....
15,"$27,022.61",-34122.00,USD,34122,333499570009,33,False,UNKNOWN,ELEATEX TRADING S.L.,ELEATEX TRADING S.L.,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207165021570793 INVOICE 666 DD 06.06.2012,pdf/METASTAR Account statement 30.06.12-31.12....
16,"$3,567.69",-4505.00,USD,4505,TR240006200034100009092916,TR,False,TR,UNIVAR,UNIVAR KIMYA SANAYI VE DIS TIC LTD.,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207165022255697 INVOICE 785 DD 13.07.2012,pdf/METASTAR Account statement 30.06.12-31.12....
17,"$4,414.00",-4414.00,EUR,5574,DE96810700000210018800,DE,False,DE,MERTIK MAXITROL GMBH&CO KG,MERTIK MAXITROL GMBH & CO.KG,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207165020041457 INVOICE 01 DD 14.07.2012,pdf/METASTAR Account statement 30.06.12-31.12....
18,$791.94,-1000.00,USD,1000,333468790001,33,False,US,LINSTAR SYSTEMS CORP.,LINSTAR SYSTEMS CORP.,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207165025774169 INVOICE 01 DD 01.05.12,pdf/METASTAR Account statement 30.06.12-31.12....
19,$22.91,28.93,USD,29,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,333455870002,33,False,VG,INMAXO CAPITAL CORP.,INMAXO CAPITAL CORP.,Company,1207165020140189 CONTRACT N 001 DD 24.12.2009,pdf/METASTAR Account statement 30.06.12-31.12....
20,"$118,791.15",150000.00,USD,150000,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,333484540002,33,False,GB,LOTA SALES LLP,LOTA SALES LLP,Company,1207165021876577 DOGOVOR ZAYMA,pdf/METASTAR Account statement 30.06.12-31.12....
21,"$118,791.15",150000.00,USD,150000,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,...,az,333504500003,33,False,GB,MOBILA LLP,MOBILA LLP,Company,1207165026198353 INVOICE.No 69 DD 13.07.2012,pdf/METASTAR Account statement 30.06.12-31.12....
22,"$125,786.00",-158832.54,USD,158833,40702840722002001727,40,False,RU,OOO MAYAKPRINT,OOO MAYAKPRINT,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207175028296266 SHOT N 156 DD 05.04.2012,pdf/METASTAR Account statement 30.06.12-31.12....
23,"$150,000.00",-150000.00,EUR,189409,AE710200000025597675100,AE,False,AE,IMEX MOTORS L.L.C,IMEX MOTORS L.L.C.,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207175026172670 INVOICE 001 DD 12.02.2012 FOR...,pdf/METASTAR Account statement 30.06.12-31.12....
24,"$145,150.00",-145150.00,EUR,183284,333488110001,33,False,NZ,JETFIELD NETWORKS LIMITED,JETFIELD NETWORKS LIMITED,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,invoice 888 dd 09.06.2012,pdf/METASTAR Account statement 30.06.12-31.12....
25,"$87,984.65",-111100.00,USD,111100,333488110001,33,False,NZ,JETFIELD NETWORKS LIMITED,JETFIELD NETWORKS LIMITED,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207175024945082 invoice 888 dd 09.06.2012,pdf/METASTAR Account statement 30.06.12-31.12....
26,"$72,400.00",-72400.00,EUR,91421,333488110001,33,False,NZ,JETFIELD NETWORKS LIMITED,JETFIELD NETWORKS LIMITED,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,invoice 888 dd 09.06.2012,pdf/METASTAR Account statement 30.06.12-31.12....
27,"$68,366.00",-68366.00,EUR,86328,TR480006400000212780107701,TR,False,TR,CAHAN ISTANBUL DIS.TIC.LTD,CAHAN ISTANBUL DIS.TIC.LTD,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207175023760670 INVOICE 2345 DD 08.07.2012,pdf/METASTAR Account statement 30.06.12-31.12....
28,"$25,342.11",-32000.00,USD,32000,DE11400400280420274300,DE,False,DE,MTG HANDELS UND CONSULTING GMBH,MTG HANDELS UND CONSULTING GMBH,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207175025570082 INVOICE 531 DD 01.04.2012,pdf/METASTAR Account statement 30.06.12-31.12....
29,"$18,598.73",-23485.00,USD,23485,333499570009,33,False,UNKNOWN,ELEATEX TRADING S.L.,ELEATEX TRADING S.L.,...,az,EE77 3300 3334 8704 0004,EE,True,GB,METASTAR INVEST LLP,METASTAR INVEST LLP,Company,1207175028320294 INVOICE 666 DD 06.06.2012,pdf/METASTAR Account statement 30.06.12-31.12....
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16910,"$105,000.00",-105000.00,EUR,130967,IT57S0504801639000000001821,IT,False,IT,FONDAZIONE NOVAE TERRAE,FONDAZIONE NOVAE TERRAE,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295036793430 PAYMENT TO THE CONTRACT N.W/N...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16911,"$91,000.00",-91000.00,EUR,113505,EE683300333516210006,EE,False,GB,FABERLEX LP,FABERLEX LP,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,GROUP PAYMENT,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16912,"$60,210.00",-75100.00,USD,75100,LI0408812105030530001,LI,False,VG,RENAISSANCE ASSOCIATES S.A.,RENAISSANCE ASSOCIATES S.A.,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295020996358 PAYMENT TO THE CONTRACT N 01 ...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16913,"$66,338.00",-66338.00,EUR,82744,TR020020600033019706260102,TR,False,TR,KARAT GUC SISTEMLERI SAN.VE TIC.,KARAT GUC SISTEMLERI SAN.VE TIC.,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295026084242 PAYMENT TO THE INVOICE N. N1-...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16914,"$64,825.00",-64825.00,EUR,80857,NL44DEUT0265165296,NL,False,NL,ENZA ZADEN EXPORT B.V,ENZA ZADEN EXPORT B.V.,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295038278546 PAYMENT TO THE INVOICE N 9554...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16915,"$55,007.00",-55007.00,EUR,68611,LI7908812105030540000,LI,False,US,PARY INTERNATIONAL,PARY INTERNATIONAL INC.,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295036593302 PAYMENT TO THE CONTRACT N 038...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16916,"$40,888.28",-51000.00,USD,51000,AE650030010220620394001,AE,False,AE,ZEN TRAX INC.,ZEN TRAX INC.,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295022190790 PAYMENT TO THE CONTRACT N 6 D...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16917,"$32,069.24",-40000.00,USD,40000,102558,10,False,UNKNOWN,CEMENA SERVICES LIMITED,CEMENA SERVICES LIMITED,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295026476422 PAYMENT TO THE CONTRACT N.28 ...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16918,"$25,000.00",-25000.00,EUR,31183,CZ5527000000002107039983,CZ,False,CZ,GLAMOUR DIAMOND S.R.O.,GLAMOUR DIAMOND S.R.O.,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295034398998 PAYMENT TO THE INVOICE N.16/1...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16919,"$20,043.28",-25000.00,USD,25000,475458233237,47,False,CN,"JIANGSU UNBEATABLE RADIATOR CO.,LTD","JIANGSU UNBEATABLE RADIATOR CO., LTD",...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295023479022 PAYMENT TO THE INVOICE N.ZA00...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16920,"$21,839.20",-21839.20,EUR,27241,FR7630003000800002030076732,FR,False,FR,GSN SEMENCES S.A.S,GSN SEMENCES S.A.S,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295036178610 PAYMENT TO THE CONTRAKT GSN/F...,pdf/HILUX Allegato 4.xml
16921,"$16,034.62",-20000.00,USD,20000,LV59RTMB0000611806345,LV,False,VG,ODEN ASSETS LTD,ODEN ASSETS LTD,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295031262686 PAYMENT TO THE CONTRACT N 398...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16922,"$7,668.05",-9564.37,USD,9565,TR420001200938800053000248,TR,False,TR,YIGITLER FLANS,YIGITLER FLANS,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295024693494 PAYMENT TO THE INVOICE N.H-8 ...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16923,"$7,040.00",-7040.00,EUR,8781,TR230006400000211373371180,TR,False,TR,SAYGIN HIDROFOR VE POMPA SIS.SAN.,SAYGIN HIDROFOR VE POMPA SIS. SAN.,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295020010390 PAYMENT TO THE INVOICE N.3281...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16924,"$6,876.00",-6876.00,EUR,8577,TR030006400000213930001995,TR,False,TR,DURKO CEVRE ENERJI TEKNIGI VE TIC.,DURKO CEVRE ENERJI TEKNIGI VE TIC.,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295024599126 PAYMENT TO THE INVOICE N.2 DD...,pdf/HILUX Allegato 4.xml
16925,"$1,892.00",-1892.00,EUR,2360,TR950003200014500000226115,TR,False,TR,GRUNDFOS POMPA SAN.TIC.LTD.STI.,GRUNDFOS POMPA SAN.TIC.LTD.STI.,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295022404822 PAYMENT FOR WATER PIPES UNDER...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16926,"$1,547.34",1930.00,USD,1930,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,EE083300333513530006,EE,False,GB,CROSSPARK LINES LLP,CROSSPARK LINES LLP,Company,1412295072206634 inv. no 1916 for electro equi...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16927,"$300,000.00",300000.00,EUR,374191,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,LV87AIZK0001140110799,LV,False,CY,CASPIAN MOBILE LTD.,CASPIAN MOBILE LTD.,Company,1412295105818062 INVOICE NO P230400506 FOR ELE...,pdf/HILUX Allegato 4.xml
16928,"$4,409,477.61",5499946.50,USD,5499947,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,AZ18IBAZ40150018404004037267,AZ,False,AZ,BAKTELEKOM MMC,BAKTELEKOM MMC,Company,1412265102334077 CONTRAKT N47 03.11.2014 /FEE...,pdf/HILUX Allegato 4.xml
16929,"$4,712,772.44",5878246.50,USD,5878247,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,AZ18IBAZ40150018404004037267,AZ,False,AZ,BAKTELEKOM MMC,BAKTELEKOM MMC,Company,1412295108133598 CONTRAKT N47 03.11.2014 /FEE...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16930,"$300,000.00",-300000.00,EUR,374191,CH62007645958754C000C,CH,False,CH,CHIANCIANESI AND LONGONI,CHIANCIANESI AND LONGONI,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412305035411964 PAYMENT TO THE INVOICE N.69 D...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16931,"$230,000.00",-230000.00,EUR,286880,LV48AIZK0001140094623,LV,False,UNKNOWN,CASPIAN INVEST LIMITED,CASPIAN INVEST LIMITED,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295033085006 PAYMENT TO THE INVOICE N.39 D...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16932,"$134,600.00",-134600.00,EUR,167887,NL91DEUT0471363170,NL,False,NL,BAARS CONFLOAT BV,BAARS CONFLOAT BV,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412295030890702 PAYMENT TO THE INVOICE N.1400...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16933,"$962,077.20",-1200000.00,USD,1200000,EE073300333514840009,EE,False,GB,DATEMILE ALLIANCE LLP,DATEMILE ALLIANCE LLP,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412315075078582 PAYMENT TO THE CONTRACT N 55 ...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16934,"$617,332.87",-770000.00,USD,770000,EE873300333520140007,EE,False,GB,RICHFIELD TRADING L.P.,RICHFIELD TRADING L.P.,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412315074763930 PAYMENT TO THE CONTRACT N.12/...,pdf/HILUX Allegato 4.xml
16935,"$80,173.10",-100000.00,USD,100000,EE123300333505040009,EE,False,GB,BONDWEST LLP,BONDWEST LLP,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412315077469974 PAYMENT TO THE CONTRACT N 28 ...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16936,"$70,552.33",-88000.00,USD,88000,EE303300333517290009,EE,False,GB,CITYPORT CONTRACTS L.P.,CITYPORT CONTRACTS L.P.,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412315075275670 CONTRACT N 0042 DD 01.08.2013,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16937,"$33,672.70",-42000.00,USD,42000,TR920006200037300009087555,TR,False,TR,VUGAR RZAYEV,VUGAR RZAYEV,...,az,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,Company,1412315020689974 PAYMENT TO THE CONTRACT N 50 ...,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16938,"$4,810.39",6000.00,USD,6000,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,EE683300333516210006,EE,False,GB,FABERLEX LP,FABERLEX LP,Company,1412315076170038 GROUP PAYMENT,pdf/HILUX Account statement 30.06.12-31.12.14.xml
16939,"$1,763,808.20",2200000.00,USD,2200000,EE12 3300 3335 1615 0001,EE,True,GB,HILUX SERVICES LP,HILUX SERVICES LP,...,az,EE923300333515620008,EE,False,GB,RASMUS LP,RASMUS LP,Company,1412315076256810 ACC TO CONTR 001 DD 03.06.201...,pdf/HILUX Account statement 30.06.12-31.12.14.xml

In [22]:
# Checking number of columns 

print(data.shape)
print(dk_data.shape)

(16940, 1)
(16940, 23)